server:
  port: 80
management:
  security:
    enabled: false #关掉安全认证,如果开启则需要引入spring-boot-starter-security配置
  port: 80
  context-path: /monitor #actuator的访问路径
endpoints:
  shutdown:
    enabled: true