spring:
  application:
    name: spring-boot-mybatis-plus-dynamic-datasource
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://39.105.15.49:3306/test01
          username: root
          password: lqhmysql
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://120.46.149.32:3306/test01
          username: root   # 只读账户
          password: guofei??

server:
  port: 8888