server:
  port: 9999
spring:
  application:
    name: spring-boot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.105.15.49:3306/test01?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: lqhmysql
    test-on-borrow: true
    test-while-idle: true
    time-between-eviction-runs-millis: 3600000
    keepAlive: true
    validationQuery: select 1
    hikari:
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 20000
      ## 最小空闲连接数量
      minimum-idle: 1
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 20
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1200000
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 300000