server:
  port: 8001

spring:
  activemq:
    broker-url: tcp://120.46.149.32:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 50
    in-memory: true
    jms:
      cache:
        session-cache-size: 5

myqueue:
  boot-activemq-queue