server:
  port: 8001

spring:
  activemq:
    broker-url:
    user: admin
    password: secret
    pool:
      enabled: true
      max-connections: 50
    in-memory: true
    jms:
      cache:
        session-cache-size: 5

myqueue:
  boot-activemq-queue